application: nombre-del-proyecto
version: 20
runtime: go113

default_expiration: "1d"

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /.*
  script: _go_app
